services:
  redis:
    image: redis:7-alpine
    container_name: beacon-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17-alpine
    container_name: beacon-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beacon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
